# Generated by Django 5.0 on 2024-01-01 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='beneficiary_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
