# Generated by Django 5.0 on 2024-01-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_groups_user_is_super_user_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super_user',
        ),
    ]
